{
 "title": "uds-proxy stats",
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "udsproxy_http_requests_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "requests" }
   ],
   "targets": [
    { "expr": "udsproxy_http_requests_total", "legendFormat": "{{code}} {{method}}" }
   ]
  },
  {
   "title": "udsproxy_http_inflight",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "requests" }
   ],
   "targets": [
    { "expr": "udsproxy_http_inflight" }
   ]
  },
  {
   "title": "Request Count / Duration",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(udsproxy_request_duration_seconds_bucket[30s])) by (le) ",
     "legendFormat": "{{le}} s"
    }
   ]
  }
 ]
}